### ISSUE TITLE
Reference error

### ISSUE THREAD

**Issue by krpot** [rdash/rdash-angular#102]
When I build the project, it give me this error:

[20:54:18] Warning: gulp version mismatch:
[20:54:18] Global gulp is 3.9.0
[20:54:18] Local gulp is 3.8.11
[20:54:19] Using gulpfile /Volumes/DocHouse/projects/ispark/rdash-angular/gulpfile.js
[20:54:19] Starting 'usemin'...
[20:54:19] Starting 'copy-bower_fonts'...
[20:54:19] Starting 'custom-images'...
[20:54:19] Starting 'custom-js'...
[20:54:19] Starting 'custom-less'...
[20:54:19] Starting 'custom-templates'...
[20:54:19] Finished 'custom-less' after 11 ms
events.js:72
        throw er; // Unhandled 'error' event
              ^
ReferenceError: Promise is not defined
    at /Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/lib/htmlBuilder.js:20:16
    at Array.map (native)
    at module.exports (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/lib/htmlBuilder.js:19:25)
    at Transform._transform (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/index.js:17:9)
    at Transform._read (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)

I'm not familiar with those JavaScript build tools, so I have no idea how to fix it. Can you please help me to solve the issue? Thank you in advance.

**Comment by Ehesp** [comment]
On: 
https://github.com/rdash/rdash-angular/blob/master/package.json#L11

Try updating this line to:

```
"gulp": "~3.9.0",
```

Then run:

`npm install`.

Try building the project again and let me know if you still have this issue.

**Comment by krpot** [comment]
Thank you for you reply. I did that but it's still same only except version mismatch related messages has gone.

**Comment by Ehesp** [comment]
Have you recently upgrade your node version?

Could you run: `node -v`. 
Might be worth removing the `node_modules` folder (`rm -rf node_modules/` on Linux machines), and rebuilding.

**Comment by krpot** [comment]
Thank you for your support again. My node.js is v.0.10.28 and it was the same error after removing node_modules folder. And I got this error when I cloned the repository again and tried:

[21:22:14] Starting 'usemin'...
[21:22:14] Starting 'copy-bower_fonts'...
[21:22:14] Starting 'custom-images'...
[21:22:14] Starting 'custom-js'...
[21:22:14] Starting 'custom-less'...
[21:22:14] Starting 'custom-templates'...
[21:22:14] Finished 'copy-bower_fonts' after 17 ms
[21:22:14] Starting 'build-assets'...
[21:22:14] Finished 'build-assets' after 7.73 μs
[21:22:14] Finished 'custom-less' after 12 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error in plugin 'gulp-usemin'
Path /Volumes/DocHouse/projects/ispark/rdash-angular/src/components/bootstrap/dist/css/bootstrap.min.css not found!
    at getFiles (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/lib/blocksBuilder.js:59:15)
    at module.exports (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/lib/blocksBuilder.js:97:20)
    at Transform._transform (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/index.js:16:22)
    at Transform._read (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Volumes/DocHouse/projects/ispark/rdash-angular/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)

**Comment by Ehesp** [comment]
You're on quite an old version of Node, latest version is 4.1.2. I'd recommend upgrading since it could be something related to that.

To upgrade:
```
sudo npm cache clean -f
sudo npm install -g n
sudo n 4.1.2
```

That error above looks like a problem with not finding bootstrap. Have you ran `bower install`?

**Comment by krpot** [comment]
Great! I have updated npm and now I have got build. Thank you very much!
