### ISSUE TITLE
Problems with Installation directions 

### ISSUE THREAD

**Issue by adilfulara** [rdash/rdash-angular#87]
Any pointers in problem investigation ?
Followed steps as per https://github.com/rdash/rdash-angular installation instructions.
Node newbie here :(

```
Adils-MacBook-Pro:rdash-angular adilfulara$ gulp build
[00:16:43] Using gulpfile ~/rdash-angular/gulpfile.js
[00:16:43] Starting 'usemin'...
[00:16:45] Starting 'copy-bower_fonts'...
[00:16:45] Starting 'custom-images'...
[00:16:45] Starting 'custom-js'...
[00:16:45] Starting 'custom-less'...
[00:16:45] Starting 'custom-templates'...
[00:16:45] Finished 'custom-less' after 11 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error in plugin 'gulp-usemin'
Path /Users/adilfulara/rdash-angular/src/components/rdash-ui/dist/css/rdash.min.css not found!
    at getFiles (/Users/adilfulara/rdash-angular/node_modules/gulp-usemin/lib/blocksBuilder.js:58:15)
    at module.exports (/Users/adilfulara/rdash-angular/node_modules/gulp-usemin/lib/blocksBuilder.js:96:20)
    at Transform._transform (/Users/adilfulara/rdash-angular/node_modules/gulp-usemin/index.js:16:22)
    at Transform._read (/Users/adilfulara/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at Transform._write (/Users/adilfulara/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/adilfulara/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/adilfulara/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Transform.Writable.write (/Users/adilfulara/rdash-angular/node_modules/gulp-usemin/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/adilfulara/rdash-angular/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/adilfulara/rdash-angular/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
```

**Comment by jcharters** [comment]
I also have this problem, running the latest node on OSX

**Comment by adamlytics** [comment]
I'm having this same issue.  Updated npm, bower, and node on latest OSX, same issue.

**Comment by adilfulara** [comment]
You need to

- reinstall bower
- reinstall gulp
- clear npm cache

That solved the problem for me. I also have

**Comment by adamlytics** [comment]
That didn't fix the issue.  I think there's something wrong with the bower config.  I'm not sure what it is, but I noticed that the contents of the src/components/rdash-ui folder are not the same as what is in the https://github.com/rdash/rdash-ui repo.  I renamed the default rdash-ui folder and then cloned that repo in its location and it works great now.  Thanks for your work on this and support.

**Comment by adilfulara** [comment]
In your gulp file, change the relative location of the bower_components folder. If i remember correctly, they pointed to folder in src/ but in my case, they were at the same level as the gulp file. 

Hope that helps.

**Comment by Ehesp** [comment]
I'll check this out ASAP... The bowerrc file should sort that out.

**Comment by kristi** [comment]
I ran into this problem today on osx. Reinstalling did not help. Bower didn't install rdash.min.css anywhere. adamlytics's hack did work.

**Comment by zavierrodriguez** [comment]
The issue here is that the downloaded code is configured slightly differently than the code in the repository.  The code in the repository contains a .bowerrc file.  This file specifies where the bower components should be placed (more info here: http://bower.io/docs/config/#directory) but the download does not have this file.  Simply create this file before running bower install and you're all set.  Its a small simple file, see here https://github.com/rdash/rdash-angular/blob/master/.bowerrc.

Just wanted to contribute a little to this great project.  Thanks friends!

**Comment by NancyRabbit** [comment]
downloaded code doesn't have app.js file, so how could the project launched?

**Comment by doender** [comment]
For me the solution was to upgrade node (somehow usemin was not working with my older node version)

**Comment by merzak7** [comment]
@NancyRabbit @adilfulara  @jcharters @adamlytics @kristi 
 
 **Verify if .bowerrc exist or not if not try this:**

**1-** Create a file with this name ".bowerrc".
**2-** Put this inside: 
``` {
  "directory" : "src/components"
}```
**3-** Reinstall npm, bower and gulp.
